# Generated by Django 3.1.1 on 2021-01-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapstudentprofile',
            name='Informational_Text_Key_Ideas_and_Details_SCORE',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mapstudentprofile',
            name='Informational_Text_Language_Craft_and_Structure_SCORE',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mapstudentprofile',
            name='Literary_Text_Key_Ideas_and_Details_SCORE',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mapstudentprofile',
            name='Literary_Text_Language_Craft_and_Structure_SCORE',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mapstudentprofile',
            name='Vocabulary_Acquisition_and_Use_SCORE',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
